version: '3'

services:
  postgres:
    image: bitnami/postgresql:16.4.0
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - kotlin_postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:8.14.0
    env_file:
      - .env
    ports:
      - 5050:80
    volumes:
      - kotlin_pgadmin_data:/var/lib/pgadmin
      - ./databases.json:/pgadmin4/servers.json
    entrypoint:
      - sh
      - -c
      - |
        echo "Loading custom servers..."
        cp /pgadmin4/servers.json /pgadmin4/.pgadmin/servers.json
        /entrypoint.sh

volumes:
  kotlin_postgres_data:
  kotlin_pgadmin_data: