spring:
  application:
      name: rest-with-spring-boot-kotlin
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
